# -----------------------------
# Ollama settings
# -----------------------------
ollama.base-url=http://ollama:11434
ollama.embed-model=llama3

# -----------------------------
# Chroma settings
# -----------------------------
chroma.base-url=http://chroma:8000
chroma.tenant=default_tenant
chroma.database=default_database
chroma.collection=pdf_collection

# -----------------------------
# PDF / Chunk settings
# -----------------------------
pdf.chunk-size=500
pdf.chunk-overlap=50